language: go

go:
  - "1.12.5"

env:
  global:
    - APP_NAME=lfserv
    - GOOS=linux
    - GOARCH=amd64

before_script:
  - mkdir build

script: go build -o build/${APP_NAME}-${GOOS}-${GOARCH} ${APP_NAME}.go
